HIT     = 0
STAND   = 1
DOUBLE  = 2
SPLIT   = 3

STRATEGY_TYPE_COLOR = {}
STRATEGY_TYPE_COLOR[HIT]    = (255, 0, 0)
STRATEGY_TYPE_COLOR[STAND]  = (255, 255, 0)
STRATEGY_TYPE_COLOR[DOUBLE] = (0, 0, 255)
STRATEGY_TYPE_COLOR[SPLIT]  = (0, 255, 0)

STRATEGY_TYPE_CAPTION = {}
STRATEGY_TYPE_CAPTION[HIT]    = "HIT"
STRATEGY_TYPE_CAPTION[STAND]  = "STAND"
STRATEGY_TYPE_CAPTION[DOUBLE] = "DOUBLE"
STRATEGY_TYPE_CAPTION[SPLIT]  = "SPLIT"

LEGAL_ACTIONS = [HIT, STAND]